models/Store.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "store".
 *
 * @property integer $id
 * @property string $name
 * @property string $adress
 * @property integer $status
 * @property integer $user_by_cr
 * @property integer $user_by_up
 * @property integer $date_cr
 * @property integer $date_up
 */
class Store extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'store';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'adress', 'status', 'user_by_cr', 'user_by_up'], 'required'],
            [['status', 'user_by_cr', 'user_by_up'], 'integer'],
            [['name', 'adress'], 'string', 'max' => 255],
            [['date_cr', 'date_up'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Наименование',
            'adress' => 'Адрес',
            'status' => 'Статус',
            'user_by_cr' => 'Создатель',
            'user_by_up' => 'Изменял', 
            'date_cr' => 'Создано',
            'date_up' => 'Изменено',
        ];
    }

    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_by_cr']);
    }
}

controllers/StoreController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Store;
use app\models\StoreSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use kartik\mpdf\Pdf;

/**
 * StoreController implements the CRUD actions for Store model.
 */
class StoreController extends BaseController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return array_merge([
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ], parent::behaviors());
    }

    /**
     * Lists all Store models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new StoreSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Store model.
     * @param integer $id
     * @return mixed
     */
    public function actionPrintlist()
    {
        
        $searchModel = new StoreSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
                   
        Yii::$app->response->format = \yii\web\Response::FORMAT_RAW;
        $headers = Yii::$app->response->headers;
        $headers->add('Content-Type', 'application/pdf');
          
        $content = $this->renderPartial('@app/views/store/liststore',[
            'dataProvider' => $dataProvider->getModels(),
        ]);
             
         $pdf = new Pdf([
            'cssFile' => '@vendor/kartik-v/yii2-mpdf/assets/kv-mpdf-bootstrap.min.css',
            'mode' => Pdf::MODE_UTF8, // leaner size using standard fonts
            'content' => $content,
            'orientation' => Pdf::ORIENT_LANDSCAPE,
        ]);
        
        //echo "<pre>".print_r($pdf,true)."</pre>";
        
        return $pdf->render();
    }
    
    /*
    Печатать документы
    */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Store model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Store();

        if ($model->load(Yii::$app->request->post())) {
            
            $model->date_cr = date('Y-m-d');
            $model->date_up = date('Y-m-d');

            $model->save();
            return $this->redirect(['index', 'id' => $model->id]);
        } else {
            return $this->render('create', [
				'title' => 'Создание склада',
                'user_by_cr_v' => Yii::$app->user->identity->id,
				'label' => 'Склады',
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Store model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {

            $model->date_up = date('Y-m-d');
            $model->save();
            return $this->redirect(['index', 'id' => $model->id]);
        } else {
            return $this->render('update', [
				'title' => 'Изменение склада',
				'label' => 'Склады',
                'user_by_cr_v' => Yii::$app->user->identity->id,
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Store model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Store model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Store the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Store::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/store/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Store */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="store-form">
 <div class="box box-default">  
        <div class="box-body"> 
    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'adress')->textInput(['maxlength' => true]) ?>

    <div style="display: none;">

        <?= $form->field($model, 'status')->textInput(['value'=>1]) ?>

        <?= $form->field($model, 'user_by_cr')->textInput(['value'=>$user_by_cr_v]) ?>

        <?= $form->field($model, 'user_by_up')->textInput(['value'=>$user_by_cr_v]) ?>

        <?= $form->field($model, 'date_cr')->textInput() ?>

        <?= $form->field($model, 'date_up')->textInput() ?>

    </div>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Создать' : 'Изменить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
</div></div>

views/store/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\StoreSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="store-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'adress') ?>

    <?= $form->field($model, 'status') ?>

    <?= $form->field($model, 'user_by_cr') ?>

    <?php // echo $form->field($model, 'user_by_up') ?>

    <?php // echo $form->field($model, 'date_cr') ?>

    <?php // echo $form->field($model, 'date_up') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/store/create.php
<?php

use yii\helpers\Html;
 

/* @var $this yii\web\View */
/* @var $model app\models\Store */

//$this->title = 'Создание Store';
$this->title = $title;
//$this->params['breadcrumbs'][] = ['label' => 'Stores', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $label, 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="store-create">

   <!--<h1><?= Html::encode($this->title) ?></h1>-->

    <?= $this->render('_form', [
        'model' => $model,
        'user_by_cr_v' => $user_by_cr_v,
    ]) ?>

</div>

views/store/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\Url;
use kartik\export\ExportMenu;

$gridColumn = [
    'id',
     'name',
     'adress',
     [
         'attribute' => 'user_by_cr',
         'value' => 'user.name',
     ], 
];
?>
<div class="store-index">

 <!--   <h1><?= Html::encode($this->title) ?></h1>-->
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

<div class="box box-default">   
    <div class="box-body">
        
       <!-- <?= Html::a('Create Store', ['create'], ['class' => 'btn btn-success']) ?>
        --><?= Html::a('Добавить', ['create'], ['class' => 'btn btn-success']) ?>
        <?= Html::a(Html::tag('i', '', ['class' => 'fa fa-print']).' Печатать', ['store/printlist'], ['class' =>'btn btn-default','target'=>"_blank"]) ?>
        <?php 
                echo ExportMenu::widget([
                    'dataProvider' => $dataProvider,
                    'columns' => $gridColumn
                ]);
            ?>
    
    </div>
</div>
<div class="box box-default">   
    <div class="box-body">
<?php Pjax::begin(); ?>    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
			

            'id',
            'name',
            'adress',
            //'status',
            //'user_by_cr',
            [
                'attribute' => 'user_by_cr',
                'value' => 'user.name',
            ],
            // 'user_by_up',
            // 'date_cr',
            // 'date_up',

            ['class' => 'yii\grid\ActionColumn',
			'template' => '{update} {delete} {link}'
			],
        ],
    ]); ?>
<?php Pjax::end(); ?></div>
</div>
</div>

views/store/liststore.php
<div class=Section1>


<table class=MsoNormalTable border=1 cellspacing=0 cellpadding=0
 style='margin-left:.25pt;border-collapse:collapse;border:none'>
 
 
 
 <tr style='height:19.85pt'>
  <td width=60 >
  <p class=MsoNormal align=center style='text-align:center'><span
  style='font-size:9.0pt'>№</span></p>
  </td>
  <td width=60 >
  <p class=MsoNormal align=center style='text-align:center'><span
  style='font-size:9.0pt'>Код</span></p>
  </td>
  <td width=150 >
  <p class=MsoNormal align=center style='text-align:center'><span
  style='font-size:9.0pt'>Наименование</span></p>
  </td>
  <td width=250 >
  <p class=MsoNormal align=center style='text-align:center'><span
  style='font-size:9.0pt'>Адрес</span></p>
  </td>
  <td width=100 >
  <p class=MsoNormal align=center style='text-align:center'><span
  style='font-size:9.0pt'>Создатель</span></p>
  </td>
  
 </tr>
 
 
 
 <?php
 $table = '';
 $number = 0;

 foreach($dataProvider as $inf)
 {
	$number++;	
	/*if($inf->type == 'person')$tip = 'Физ. лицо';
	else $tip = 'Юр. лицо'*/;
	 echo "dfvdf";
	$table .= "
	
	 <tr >
		<td width=60 >
		<p class=MsoNormal align=center ><span lang=EN-US
		style='font-size:9.0pt'>".$number."</span></p>
		</td>
 
		<td width=60 >
		<p class=MsoNormal style='margin-left:2.85pt'><span lang=EN-US
		style='font-size:8.0pt;font-family:'Arial Narrow','sans-serif''>".$inf->id."</span></p>
		</td>

		<td width=150 >
		<p class=MsoNormal style='margin-left:2.85pt'><span lang=EN-US
		style='font-size:8.0pt;font-family:'Arial Narrow','sans-serif''>".$inf->name."</span></p>
		</td>
		
	  
		<td width=250 >
		<p class=MsoNormal align=center style='text-align:center'><span lang=EN-US
		style='font-size:9.0pt'>".$inf->adress."</span></p>
		</td>	
		
		<td width=100 >
		<p class=MsoNormal align=center style='text-align:center'><span lang=EN-US
		style='font-size:9.0pt'>".$inf->user->name."</span></p>
		</td>

	 </tr>
		
	";
 
 } 
 echo $table; 
 
 ?>
 
</table>


</div>

views/store/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Store */

//$this->title = 'Изменение Store: ' . $model->name;
$this->title = $title ." : ". $model->name;
$this->params['breadcrumbs'][] = ['label' => $label, 'url' => ['index']];
//$this->params['breadcrumbs'][] = ['label' => 'Stores', 'url' => ['index']];
//$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Изменение';
?>
<div class="store-update">

 <!--   <h1><?= Html::encode($this->title) ?></h1>-->

    <?= $this->render('_form', [
        'model' => $model,
        'user_by_cr_v' => $user_by_cr_v,
    ]) ?>

</div>

views/store/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Store */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Stores', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="store-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'adress',
            'status',
            'user_by_cr',
            'user_by_up',
            'date_cr',
            'date_up',
        ],
    ]) ?>

</div>