models/User.php
<?php

namespace app\models;

use Yii;
use app\base\AppActiveQuery;
use yii\behaviors\BlameableBehavior;
use yii\web\ForbiddenHttpException;

/**
 * This is the model class for table "user".
 *
 * @property integer $id
 * @property string $username
 * @property string $name
 * @property string $phone
 * @property string $auth_key
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property string $permission
 * @property integer $percent_sale
 * @property integer $percent_service
 * @property integer $percent_finish
 * @property integer $status
 * @property integer $user_by_cr
 * @property integer $user_by_up
 * @property integer $date_cr
 * @property integer $date_up
 * @property integer $company
 */
class User extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    /*const ROLE_ADMIN = 999;
    const ROLE_MANAGER = 888;
    const ROLE_USER = 10;*/
    const USER_TYPE_ADMIN = 'admin';
    const USER_TYPE_MANAGER = 'maneger';
    const USER_TYPE_SUPER_ADMIN = 'super_admin';

    public static function tableName()
    {
        return 'user';
    }

    public function behaviors()
    {        
        return [
            [
                'class' => BlameableBehavior::class,
                'createdByAttribute' => 'company_id',
                'updatedByAttribute' => null,
                'value' => function($event) {
                    if (isset(Yii::$app->user->identity->id)) return Yii::$app->user->identity->company_id;
                    else return null;
                },
            ],
        ];
    }

    public static function find()
    {
        if (isset(Yii::$app->user->identity->id)){
            $companyId = Yii::$app->user->identity->company_id;
        } else {
            $companyId = null;
        }

        return new AppActiveQuery(get_called_class(), [
            'companyId' => $companyId,
        ]);
    }
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['username', 'name', 'phone', 'auth_key',  'email', 'permission', 'percent_sale', 'percent_service', 'percent_finish', 'user_by_cr', 'user_by_up', 'date_cr', 'date_up'], 'required'],
            [['name'], 'string', 'max' => 255],
            [['percent_sale', 'percent_service', 'percent_finish', 'status', 'user_by_cr', 'user_by_up', 'date_cr', 'date_up','company', 'move'], 'integer'],
            [['username', 'password_hash', 'password_reset_token', 'email'], 'string', 'max' => 255],
            [[ 'phone','auth_key', 'permission'], 'string', 'max' => 32],
            [['phone','username'], 'unique'],
            [['email'], 'unique'],
            [['password_reset_token'], 'unique'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Логин',
            'name' => 'ФИО',
            'phone' => 'Телефон',
            'auth_key' => 'Пароль',
            'password_hash' => 'Password Hash',
            'password_reset_token' => 'Password Reset Token',
            'email' => 'Email',
            'permission' => 'Должность',
            'percent_sale' => 'За продажу(%)',
            'percent_service' => 'За обслуживание(%)',
            'percent_finish' => 'За выполнение(%)',
            'status' => 'Статус',
            'user_by_cr' => 'Создатель',
            'user_by_up' => 'Изменял', 
            'date_cr' => 'Создано',
            'date_up' => 'Изменено',
            'move' => 'Доступ для перемешения',
        ];
    }
	
	public function beforeSave($insert)
	{
		if (parent::beforeSave($insert)) {
            
            if (isset(Yii::$app->user->identity->id)) {
                $log = new Logs([
                    'user_id' => Yii::$app->user->identity->id,
                    'event_datetime' => date('Y-m-d H:i:s'),
                    'event' => Logs::EVENT_USER_ADDED,
                ]);
                $log->description = $log->generateEventDescription();
                $log->save();
            }
            else {
                $log = new Logs([
                    'user_id' => null,
                    'event_datetime' => date('Y-m-d H:i:s'),
                    'event' => Logs::EVENT_USER_ADDED,
                ]);
                $log->description = $log->generateEventDescription();
                $log->save();
            }

			$this->password_hash =md5($this->auth_key);
			$this->company = \Yii::$app->user->getIdentity()->company;
			return true;
		} else {
			return false;
		}
	}
	
	public function afterSave($insert, $changedAttributes)
	{
			if ($this->permission == "admin"){
				$auth = Yii::$app->authManager;
				$admin = $auth->getRole('admin'); // Получаем роль admin
				$auth->assign($admin, $this->id);
			}elseif ($this->permission == "maneger"){
				$auth = Yii::$app->authManager;
				$maneger = $auth->getRole('maneger'); // Получаем роль meneger
				$auth->assign($maneger, $this->id);
			}elseif ($this->permission == "master"){
				$auth = Yii::$app->authManager;
				$master = $auth->getRole('master'); // Получаем роль master
				$auth->assign($master, $this->id);
			}else{
				$auth = Yii::$app->authManager;
				$guest = $auth->getRole('guest'); // Получаем роль guest
				$auth->assign($guest, $this->id);
			}
	}

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompanies()
    {
        return $this->hasMany(Companies::className(), ['admin_id' => 'id']);
    }

    public static function findByEmail($email)
    {
        return static::findOne(['email' => $email]);
    }

}

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends BaseController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return array_merge([
            'companies' => [
                'class' => \app\filters\CompaniesFilter::class,
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ], parent::behaviors());
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
		
		
		$model =$this->findModel($id);
		
		$userCr = User::find()->where(['id'=>$model->user_by_cr])->one();
		$userUp = User::find()->where(['id'=>$model->user_by_up])->one();
		//Создатель и редактор
		if (isset($userCr->name) ){ $model->user_by_cr = $userCr->name;}else{$model->user_by_cr ="Не задан";}
		if (isset($userUp->name) ){ $model->user_by_up = $userUp->name;}else{$model->user_by_up ="Не задан";}
	
		 
		 
		if ($model->permission == 'admin'){
			$model->permission = 'Администратор'; 
		 }
		  if ($model->permission == 'maneger'){
			$model->permission  = 'Менеджер'; 
		 }
		  if ($model->permission == 'master'){
			$model->permission = 'Мастер'; 
		 }
		 
		 if ($model->status == '1'){
			$model->status = 'Доступ'; 
		 }else{
			$model->status = 'Без доступа';  
		 }
		 

       return $this->render('view', [
			'title' => 'Просмотр сотрудника: ',
			'label' => 'Сотрудники',
            'model' => $model,
       ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
				'user_by_cr_v' => Yii::$app->user->identity->id,
				'user_by_up_v' => Yii::$app->user->identity->id,
				'date_cr_v' =>time(),
                'date_up_v' => time(),
				'title' => 'Создать сотрудника',
				'label' => 'Сотрудники',
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
		
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
			//echo "<pre>".print_r($model,true)."</pre>";
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
				'user_by_cr_v' => $model->user_by_cr,
				'user_by_up_v' => Yii::$app->user->identity->id,
				'date_cr_v' => $model->date_cr,
                'date_up_v' => time(),
				'title' => 'Изменить сотрудника: ',
				'label' => 'Сотрудники',
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form">
 <div class="box box-default">  
        <div class="box-body"> 
    <?php $form = ActiveForm::begin(); ?>

    
	<div class="row">
        <div class="col-md-4">
		    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
		</div>
		<div class="col-md-4">
		    <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>
		</div>
		<div class="col-md-4">
        	<?= $form->field($model, 'auth_key')->textInput(['maxlength' => true]) ?>
        </div>
	</div>

	<div class="row">
		<div class="col-md-3">
        	<?= $form->field($model, 'move')->dropDownList(
        		[
					'1'=>'Есть',
					'0'=>'Нет'
				] ,
				['prompt' => 'Выберите один вариант']);
			?>
        </div>
        <div class="col-md-3">
        	<?= $form->field($model, 'phone')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-3">
        	<?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-3">
        	<?= $form->field($model, 'permission')->dropDownList(
        		[
					'admin'=>'Администратор',
					'maneger'=>'Менеджер',
					'master'=>'Мастер'
				] ,
				['prompt' => 'Выберите один вариант']);	?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-3">
        	<?= $form->field($model, 'status')->dropDownList(
        		[
					'1'=>'Доступ',
					'0'=>'Без доступа'
				] ,
				['prompt' => 'Выберите один вариант']);
			?>
        </div>
        <div class="col-md-3">
        	<?= $form->field($model, 'percent_sale')->textInput() ?>
        </div>
        <div class="col-md-3">
        	<?= $form->field($model, 'percent_service')->textInput() ?>
        </div>
        <div class="col-md-3">
        	<?= $form->field($model, 'percent_finish')->textInput() ?>
        </div>
    </div>	
	
	<div style="display:none">
    <?= $form->field($model, 'user_by_cr')->textInput(['value'=>$user_by_cr_v]) ?>

    <?= $form->field($model, 'user_by_up')->textInput(['value'=>$user_by_up_v]) ?>

     
    <?= $form->field($model, 'date_cr')->textInput(['value'=>$date_cr_v]) ?>

    <?= $form->field($model, 'date_up')->textInput(['value'=>$date_up_v]) ?>
	</div>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Создать' : 'Изменить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
</div>
</div>

views/user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'phone') ?>

    <?= $form->field($model, 'auth_key') ?>

    <?php // echo $form->field($model, 'password_hash') ?>

    <?php // echo $form->field($model, 'password_reset_token') ?>

    <?php // echo $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'permission') ?>

    <?php // echo $form->field($model, 'percent_sale') ?>

    <?php // echo $form->field($model, 'percent_service') ?>

    <?php // echo $form->field($model, 'percent_finish') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'user_by_cr') ?>

    <?php // echo $form->field($model, 'user_by_up') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/create.php
<?php

use yii\helpers\Html;
 

/* @var $this yii\web\View */
/* @var $model app\models\User */

//$this->title = 'Создание User';
$this->title = $title;
//$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $label, 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">

   <!--<h1><?= Html::encode($this->title) ?></h1>-->


    <?= $this->render('_form', [
		'user_by_cr_v' => $user_by_cr_v,
		'user_by_up_v' => $user_by_up_v,
		'date_cr_v' => $date_cr_v,
		'date_up_v' => $date_up_v,
        'model' => $model,
    ]) ?>

</div>

views/user/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\Url;
use kartik\export\ExportMenu;
use app\models\User;

$gridColumn = [
    'name:ntext',
    'phone',
    [
      'attribute'=>'permission',
      'filter'=>array("admin"=>"Администратор","maneger"=>"Менеджер","master"=>"Мастер"),
      'content'=>function($data){
        if ($data->permission == 'admin'){
          return 'Администратор'; 
        }
        if ($data->permission == 'maneger'){
          return 'Менеджер'; 
        }
        if ($data->permission == 'master'){
        return 'Мастер'; 
        }
      },
    ],       
    'percent_sale',
    'percent_service',
    'percent_finish',
    [
     'attribute'=>'status',
     'filter'=>array("1"=>"Доступ","0"=>"Без доступа"),
     'format'=>'boolean',
    ],
];
?>
<div class="user-index">
  <div class="box box-default">  
    <div class="box-body"> 
        <?= Html::a('Добавить', ['create'], ['class' => 'btn btn-success']) ?>
        <?php 
          echo ExportMenu::widget([
              'dataProvider' => $dataProvider,
              'columns' => $gridColumn
          ]);
        ?>           
    </div>
  </div>
  <div class="box box-default">  
    <div class="box-body">
      <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
    		'formatter' => [
            'class' => 'yii\i18n\Formatter',
            'booleanFormat' => [ 'Без доступа','Доступ'],
    		],
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            
            'name:ntext',
            'phone',             
      			[
              'attribute'=>'permission',
              'filter'=>array("admin"=>"Администратор","maneger"=>"Менеджер","master"=>"Мастер"),
      			  'content'=>function($data){
                if ($data->permission == 'admin'){
                  return 'Администратор'; 
                }
                if ($data->permission == 'maneger'){
                  return 'Менеджер'; 
                }
                if ($data->permission == 'master'){
                return 'Мастер'; 
                }
              },
      			],			 
             'percent_sale',
             'percent_service',
             'percent_finish',
      			 [
      				'attribute'=>'status',
      				'filter'=>array("1"=>"Доступ","0"=>"Без доступа"),
      				'format'=>'boolean',
      			 ],

            [
              'class' => 'yii\grid\ActionColumn',
        			'template' => '{leadView} {leadUpdate} {leadDelete}',
              'buttons'  => [

                  'leadView' => function ($url, $model) {
                      $url = Url::to(['/user/view', 'id' => $model->id]);
                      return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', $url, ['role'=>'modal-remote','title'=>'', 'data-toggle'=>'tooltip']);
                  },
                  'leadUpdate' => function ($url, $model) {
                      $url = Url::to(['/user/update', 'id' => $model->id]);
                      return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, ['role'=>'modal-remote','title'=>'', 'data-toggle'=>'tooltip']);
                  },
                  'leadDelete' => function ($url, $model) {
                    if($model->permission != User::USER_TYPE_ADMIN && $model->permission != User::USER_TYPE_SUPER_ADMIN){
                      $url = Url::to(['/user/delete', 'id' => $model->id]);
                      return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, [
                          'role'=>'modal-remote','title'=>'', 
                                'data-confirm'=>false, 'data-method'=>false,
                                'data-request-method'=>'post',
                                'data-toggle'=>'tooltip',
                                'data-confirm-title'=>'Подтвердите действие',
                                'data-confirm-message'=>'Вы уверены что хотите удалить этого элемента?',
                      ]);
                    }
                  },
              ]
        		],
        ],
    ]); ?>
</div>
</div>
</div>

views/user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User */

//$this->title = 'Изменение User: ' . $model->name;
$this->title = $title . $model->name;
$this->params['breadcrumbs'][] = ['label' => $label, 'url' => ['index']];
//$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
//$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Изменение';
?>
<div class="user-update">

 <!--   <h1><?= Html::encode($this->title) ?></h1>-->


    <?= $this->render('_form', [
		'user_by_cr_v' => $user_by_cr_v,
		'user_by_up_v' => $user_by_up_v,
		'date_cr_v' => $date_cr_v,
		'date_up_v' => $date_up_v,
        'model' => $model,
    ]) ?>

</div>

views/user/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = $title . $model->name;
$this->params['breadcrumbs'][] = ['label' => $label, 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-view">
 <div class="box box-default">  
        <div class="box-body"> 
    <!--<h1><?= Html::encode($this->title) ?></h1>-->

    <p>
        <?= Html::a('Изменить', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
       
    </p>

	<?
		
		
	?>
    <?= DetailView::widget([
        'model' => $model,	
        'attributes' => [
            'id',
            'username',
            'name:ntext',
            'phone',
            'auth_key',
            'password_hash',
            'password_reset_token',
            'email:email',
			'permission',
            'percent_sale',
            'percent_service',
            'percent_finish',
            'status',
            'user_by_cr',
            'user_by_up',
            [
				'attribute' => 'date_cr',
				'format' => ['datetime', 'php:d.m.Y H:i:s']
            ],
			[
				'attribute' => 'date_up',
				'format' => ['datetime', 'php:d.m.Y H:i:s']
            ],
        ],
    ]) ?>

</div>
</div>
</div>